### PR TITLE
Refresh Rate in Settings section.

### PR DESCRIPTION
**Pull request by namaskaragusthi**

### CODE REVIEW

**Comment by hpnightowl** [comment]
https://github.com/LineageOS/android_packages_apps_Settings/commit/8e061c520e6f0710174ca37041219b6a5bed1dde

https://github.com/LineageOS/android_packages_apps_Settings/commit/fb6cf9d78ee4cec82a128baf0e8601eed708238d

can you pick these and try ? because instead of changing the aosp file it is better to have  a separate java file and override it.

**Comment by hpnightowl** [comment]
You can force push :) here  after rebase

**Comment by namaskaragusthi** [comment]
> [LineageOS/android_packages_apps_Settings@8e061c5](https://github.com/LineageOS/android_packages_apps_Settings/commit/8e061c520e6f0710174ca37041219b6a5bed1dde)
> 
> [LineageOS/android_packages_apps_Settings@fb6cf9d](https://github.com/LineageOS/android_packages_apps_Settings/commit/fb6cf9d78ee4cec82a128baf0e8601eed708238d)
> 
> can you pick these and try ? because instead of changing the aosp file it is better to have a separate and java file and override it.

okay will try

**Comment by namaskaragusthi** [comment]
still under testing, don't mind...

**Pull request closed without merging**
